apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ebs-demo-bravo
  region: us-east-1
  version: "1.31"

iam:
  withOIDC: true
  podIdentityAssociations:
  - namespace: kube-system
    serviceAccountName: ebs-csi-controller-sa
    wellKnownPolicies:
      ebsCSIController: true

addons:
  - name: eks-pod-identity-agent
    tags:
      team: eks
  - name: aws-ebs-csi-driver
    version: latest
  - name: snapshot-controller
    version: latest

managedNodeGroups:
  - name: managed-ng-1
    instanceType: m5.large
    minSize: 2
    maxSize: 4
    desiredCapacity: 3